### ISSUE TITLE
"WARNING: No data from miner"

### ISSUE THREAD

**Issue by sheminasalam** [bds89/miner2mqtt#1]
I have been trying to make this work with ubuntu for my Trex miner. I am getting message "WARNING: No data from miner".
The following is my config.
```
MINER: Trex
SUDO_PASS: passwor
MQTT:
  TOPIC: miner2mqtt/ther
  HOST: 192.168.xx.xxx
  USERNAME: sxxxx
  PASS: xxxxx
INTERVAL: 20
INCLUDE:
- active_pool
- gpus
- sys_params
EXCLUDE: {}
```

I have enabled api key for Trex. Could it be the reason?

**Comment by bds89** [comment]
Yes, the error is due to the set API KEY. I updated to version 1.3 which fixed this. You need to add the parameter 
"TrexAPIPASS: YourWebGuiPassword" to config.yaml and if your API address differs from the default, also add the parameter "TrexAPI: http://127.0.0.1:хххх".

**Comment by sheminasalam** [comment]
Hi thanks for the reply. I tried the new update with the changed config. But now I am getting the following error.

```
M2M started
Set interval: 0:00:20
Unable to init server: Could not connect: Connection refused

ERROR: The control display is undefined; please run `nvidia-settings --help` for usage information.
```
Please note I havent connected any display to the system

**Comment by sheminasalam** [comment]
The problem came because I was trying to run it in SSH. Within desktop, its woring. Thanks for the help. Appreciate the good work

**Comment by sheminasalam** [comment]
Is there a way to get the uptime of the miner from this?

**Comment by bds89** [comment]
yes, in config.yaml you have to specify
INCLUDE:
- uptime.
Or you can leave the field empty (INCLUDE : {}), then the MQTT topic will match the output of the miner: https://github.com/trexminer/T-Rex/wiki/API

You need to add a sensor to Home Assistant:
   -platform:mqtt
     name: "Node3_uptime"
     state_topic: "miner2mqtt/rig3"
     value_template: "{{ (value_json.uptime |int | timestamp_custom('%H:%M:%S', False)) }}"
     device_class: timestamp
     expire_after: 660

**Comment by bds89** [comment]
yes, in config.yaml you have to specify
```yaml
INCLUDE:
- uptime.
```

Or you can leave the field empty 
```yaml
INCLUDE : {}
```
then the MQTT topic will match the output of the miner: https://github.com/trexminer/T-Rex/wiki/API
You need to add a sensor to Home Assistant:
```yaml
  - platform: mqtt
    name: "Node3_uptime"
    state_topic: "miner2mqtt/rig3"
    value_template: "{{ (value_json.uptime |int | timestamp_custom('%H:%M:%S', False)) }}"
    device_class: timestamp
    expire_after: 660   
```

**Comment by sheminasalam** [comment]
That worked

**Comment by sheminasalam** [comment]
I have seen an issue. The app doesn't reconnect to the miner if the miner restarts due to some issue. After restart of miner, I can see the message ```WARNING: No data from miner``` in the app terminal. As a result I have to close the app after miner restart and relaunch it again. I don't know if it is specific to mine but it would be great if the app can reconnect after miner restart.

**Comment by bds89** [comment]
Yes, I didn't take that into account.  Authorization in the miner occurs once at startup, a little later I will try authorization again.

**Comment by bds89** [comment]
Version 1.3.1 should reconnect with the update interval specified in 'config.yaml'.
```yaml
INTERVAL: 300
```

**Comment by sheminasalam** [comment]
This worked. Appreciate the good work.

Is there a way to remote shutdown and then restart the mining with this app? 
I have my mining rig connected to my online UPS. Other than mining, there are some other essential services running on it. If there is a power outage I want to stop the mining so that the power taken by the Rig is at minimal and when the electricity comes back I can restart the mining. This can increase the battery backup. 

Since there are options for fan and power control I was wondering such a feature is already there or can be implemented?

**Comment by bds89** [comment]
Yes it is possible. To pause the miner, you must public the state OFF to the topic: `yourmqtttopic/to_miner/0(number of card)/state` To continue mining, public ON.
Unfortunately the recieved state topic doesn't work well, because I'm trying to determine the disabled state of the video card by its power_limit, but this value is different on different cards, and it's never 0. The recieved state topic: `yourmqtttopic/from_miner/0(number of card)/state`.
To implement this in home assistant, create an automation:
```yaml
action:
- service: mqtt.publish
```
Or, if you added the power_limit entity like in my example:
```yaml
light:
  - platform: mqtt
    name: "GPU0_power_limit"
    state_topic: "miner2mqtt/rig0/from_miner/0/state"
    command_topic: "miner2mqtt/rig0/to_miner/0/state"
    icon: mdi:lightning-bolt-circle
    brightness_scale: 240
    max_mireds: 240
    min_mireds: 100
    brightness_state_topic: "miner2mqtt/rig0/from_miner/0/power_limit"
    brightness_command_topic: "miner2mqtt/rig0/to_miner/0/power_limit"
```
, create an automation: 
```yaml
action:
- service: light.turn_off
```
The `light.turn_on` and `light.turn_off` services in the home assistant work even if the light is already on/off, so don't worry about bad recieved state topic.
